py_library(
    name = "carla_client",
    srcs = ["carla_client.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "keyboard_control",
    srcs = ["keyboard_control.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "sensor",
    srcs = ["sensor.py"],
    visibility = ["//visibility:public"],
)
