py_library(
    name = "carla_client",
    srcs = ["carla_client.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "manual_control",
    srcs = ["manual_control.py"],
    visibility = ["//visibility:public"],
)
