py_library(
    name = "carla_client",
    srcs = ["carla_client.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "keyboard_control",
    srcs = ["keyboard_control.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "sensors",
    srcs = ["sensors.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "controller",
    srcs = ["controller.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "viewer",
    srcs = ["viewer.py"],
    visibility = ["//visibility:public"],
)